---
title: "heights and weights around the world"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(ggplot2)
library(plotly)
library(plyr)
library(dplyr)
library(flexdashboard)


file = "./allCountries.RData"
data = readRDS(file)

# dane dla Francji
fr_data = subset(data, country == 'FR')

```


France data
=======================================================================

Column
-----------------------------------------------------------------------

### Distribution of weights for the years 1880 and 1980

```{r}

p = ggplot(fr_data, aes(x = height, fill = factor(year))) +
  geom_histogram(binwidth = 5, alpha = 0.5, position = "identity") +
  labs(x = "Height",
       y = "Density") +
  facet_wrap(~sex)

ggplotly(p)

```

### Distribution of heights for the years 1880 and 1980

```{r}

p = ggplot(fr_data, aes(x = weight, fill = factor(year))) +
  geom_histogram(binwidth = 5, alpha = 0.5, position = "identity") +
  labs(x = "Weight",
       y = "Density") +
  facet_wrap(~sex)

ggplotly(p)

```

Column
-----------------------------------------------------------------------

### Distribution of BMI for the years 1880 and 1980

```{r}

p = ggplot(fr_data, aes(x = bmi, fill = factor(year))) +
  geom_density(alpha = 0.5) +
  labs(x = "BMI",
       y = "Density") +
  facet_wrap(~sex)

ggplotly(p)

```

### Comparison of average weight between the years 1880 and 1980

```{r}

p = ggplot(fr_data, aes(x = factor(year), y = weight, fill = factor(year))) +
  geom_boxplot() +
  labs(x = "Year",
       y = "Weight") +
  facet_wrap(~sex)

ggplotly(p)

```


France v country data
=======================================================================

Column
-----------------------------------------------------------------------

### Comparison of average weight between french people and selected country in selected year in selected sex

```{r}
output$weight_plot <- renderPlotly({
  p_weight <- ggplot(subset(data, country %in% c('FR', input$country) & sex %in% input$sex),
                     aes(x = factor(year), y = weight, fill = country)) +
    geom_bar(stat = "summary", fun = "mean", position = "dodge") +
    labs(x = "Year",
         y = "Average Weight",
         fill = "Country") +
    facet_wrap(~sex)

  ggplotly(p_weight)
})

plotlyOutput('weight_plot')
```

### Comparison of average height between french people and selected country in selected year in selected sex

```{r}
output$height_plot <- renderPlotly({
  p_height <- ggplot(subset(data, country %in% c('FR', input$country) & sex %in% input$sex),
                     aes(x = factor(year), y = height, fill = country)) +
    geom_bar(stat = "summary", fun = "mean", position = "dodge") +
    labs(x = "Year",
         y = "Average Height",
         fill = "Country") +
    facet_wrap(~sex)

  ggplotly(p_height)
})

plotlyOutput('height_plot')
```

Column
-----------------------------------------------------------------------

### Small 'data cloud' of weight by height data of selected sex in France and selected country

```{r}
output$scatter_plot <- renderPlotly({
  sampled_data <- data %>%
    filter(country %in% c('FR', input$country) & sex %in% input$sex) %>%
    group_by(country) %>%
    sample_n(150)

  p_scatter <- ggplot(sampled_data, aes(x = height, y = weight, color = country)) +
    geom_point(alpha = 0.7, size = 2) +
    labs(x = "Height",
         y = "Weight",
         color = "Country") +
    facet_wrap(~sex)

  ggplotly(p_scatter)
})

plotlyOutput('scatter_plot')
```

### Filters
```{r}
selectInput("country", "country:", choices = unique(data$country), selected = 'AF')
checkboxGroupInput("sex", "sex:", choices = unique(data$sex), selected = c("male", "female"))
```


All countries
=======================================================================

Column
-----------------------------------------------------------------------

### Histogram of selected parameter in selected countries

```{r}
# Rysowanie histogramu wybranego parametru dla wybranych krajów
output$hist_plot <- renderPlot({

  # Filtracja danych na podstawie wybranych krajów
  filtered_data <- data %>%
    filter(country %in% input$hist_countries)

  # Wybór kolumny dla wybranego parametru
  parameter_column <- switch(input$hist_parameter,
                             "height" = height,
                             "weight" = weight)

  # Wykres histogramu
  ggplot(filtered_data, aes(x = !!sym(parameter_column))) +
    geom_histogram(fill = "skyblue", color = "black", bins = 30) +
    facet_wrap(~country, scales = "free") + # Facetowanie na podstawie krajów
    labs(x = input$hist_parameter, y = "Frequency", 
         title = paste("Histogram of", input$hist_parameter, "in selected countries")) +
    theme_bw(base_family="Lato") +
    theme(
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      panel.border=element_blank(),
      axis.text=element_text(size=8),
      axis.title=element_text(size=10,face="bold"),
      plot.title=element_text(size=14, face="bold"),
      strip.text = element_text(size = 8, face = "bold")
    )
})

plotlyOutput('hist_plot')
```

### Filters
```{r}
selectInput("parameter", "parameter:", choices = c('height', 'weight'), selected = 'height')
checkboxGroupInput("countries", "country:", choices = unique(data$country), selected = unique(data$country))
```

Column
-----------------------------------------------------------------------

### Dumbbell plot

```{r}
output$dumbbell_plot <- renderPlot({
  filtered_data <- data %>%
    filter(year == input$dumbbell_year)

  parameter_column <- switch(input$dumbbell_parameter,
                             "height" = height,
                             "weight" = weight)

  ggplot(filtered_data, aes(x = !!sym(parameter_column), y = country)) +
    geom_line(linewidth = 3, color = "grey") +
    geom_point(aes(color = sex), size = 3, show.legend = FALSE) +
    scale_color_brewer(palette = "Set1", direction = 1) +
    theme(legend.position = "right") +
    
    geom_text(data=filter(filtered_data, country=="Czarnogóra" & sex == "female"),
              aes(x=!!sym(parameter_column), y=country, label="Female"),
              color="red", size=3, vjust=-1.5, fontface="bold", family="Lato") +
    
    geom_text(data=filter(filtered_data, country=="Czarnogóra" & sex == "male"),
              aes(x=!!sym(parameter_column), y=country, label="Male"),
              color="blue", size=3, vjust=-1.5, fontface="bold", family="Lato") +
    
    geom_text(aes(label=!!sym(parameter_column)), color="black", size=2.75, vjust=2.5, family="Lato") +

    geom_rect(aes(xmin=190, xmax=200, ymin=-Inf, ymax=Inf), fill="#EBEBEB") +
    geom_text(aes(label="Difference", y=country, x=195), fontface="bold", size=3, family="Lato") +
    geom_text(data=filter(filtered_data, country=="Czarnogóra"),
              aes(x=195, y=country, label="Difference"),
              color="black", size=3.1, vjust=-2, fontface="bold", family="Lato") + 
    
    scale_x_continuous(expand=c(0,0), limits=c(130, 200)) +
    scale_y_discrete(expand=c(0.1,0)) + 

    labs(x=NULL, y=NULL, title="", subtitle="", caption="MG") +
    
    theme_bw(base_family="Lato") +
    theme(
      panel.grid.major=element_blank(),
      panel.grid.major.y = element_line(color = "grey",size=0.3),
      panel.grid.minor=element_blank(),
      panel.border=element_blank(),
      axis.ticks=element_blank(),
      axis.text.x=element_blank(),
      plot.title=element_text(size = 16, face="bold"),
      plot.title.position = "plot",
      plot.subtitle=element_text(face="italic", size=12, margin=margin(b=12)),
      plot.caption=element_text(size=8, margin=margin(t=12), color="#7a7d7e")
    )
})

plotlyOutput('dumbbell_plot')
```

### Filters
```{r}
selectInput("dumbbell_parameter", "parameter:", choices = c('height', 'weight'), selected = 'height')
selectInput("dumbbell_year", "year:", choices = c(1880, 1980), selected = 1880)

# cos robil: https://chat.openai.com/share/39a055ce-fef6-4990-9d09-461d4689d96e
```
